---
title: "The Gimmick Scale"
description: |
  Quantifying the Consistency of Pokemon: Best of 3 vs Best of 1
author:
  - name: melondonkey
    url:
      {https://pokemon-data-analysis.netlify.app}
date: 2024-08-24
output:
  distill::distill_article:
    self_contained: true
---

If you've played VGC for a while, you probably already have an intrinsic understanding that some Pokemon are good only because of their surprise factor in closed team sheet, best-of-one ladder play.  Other Pokemon shine in best-of-three formats, which are the staple of most competitive tournaments (online tournaments excluded).  

With Generation 9, we have seen an even larger swing towards consistency with the advent of open team sheets.  While most players who are actually good at competitive Pokemon seem to really appreciate this change, Kyurem White players like myself have absolutely hated it.  The element of surprise is now gone, and I-- I mean some people in a hypothetical situation--can no longer tera ground earth power a Miraidon on turn one and win the match.  C'est la vie. 

Fortunately Showdown! has created formats for both best of one players and best of three players.  This offers a perfect natural experiment to test our hypotheses about which mons are only good because of their element of surprise, and which are good because they are actually--well, good.  So let's dive into the data.

## The Analysis

To conduct this analysis, I downloaded Showdown! data from Smogon for July 2024 in the VGC2024 Regulation G format.  There are two metas we will be examining--best of one and best of three.  

To measure a Pokemon's "gimmickiness", I propose we look at the relative likelihood that a Pokemon will be used in Bo1 compared to Bo3, or its Bo1 usage divided by its Bo3 usage.  I will filter out Pokemon that do not have at least .5% usage in either format as the relative likelihoods when very small can show us Pokemon that no one really cares about (but shhh actually I kept lowering this threshold until Kyurem White showed up in the data).  Smogon also only gives us the data tiered by elo rating.  Rather than selecting one specific elo tier though I decided to average the usage of Pokemon across all elo tiers.  Most players play in the "0" tier that goes up to 1500 so I wanted the analysis to be relevant to them.  However, it's worth noting that mon usage does not really vary that much across tiers, especially at the top end of usage.


## The Results

So are you ready to see the results?  The table below is fairly straightforward.  A gimmick-factor of 1 means that the mon is equally likely to be encountered in Bo1 and Bo3.  Values high above 1 mean the mon is more likely to be a Bo1 mon, and values below 1 indicate more likely to be Bo3.

```{r, echo=FALSE, include=FALSE}
library(DT)
library(dplyr)
df <- readr::read_csv('~/Desktop/rrr/alola/gimmick-mons.csv')

df %>%
  arrange(desc(gimmick_factor)) %>%
  mutate(
    usage = round(usage,3),
    bo3_use = round(bo3_use,3),
    gimmick_factor = round(gimmick_factor, 2)
  ) %>%
  datatable(
    options = list(scrollX = TRUE, pageLength = 200)
  ) 
```


## Commentary

Man those Alolan Muk teams are annoying, aren't they!?  More interesting than the most gimmicky mons are actually the least gimmicky that ended up being important in worlds: Ogerpon (Fire and Stone but not Water), Iron Hands, Farigaraf, Caly-S, Amoonguss--mons we know we should use if we're good at the game.

Surprisingly for this meta, Ditto was right in the middle.  While usually considered a gimmick mon, I think Ditto was taken seriously as a counter to Caly-S in this meta.  Pelipper, Landorus, and Caly-I were also mons that everyone could agree on.  

On the gimmick side were the usual suspects: Regigigas, Weezing (though Galarian Weezing had a much higher consistency rating), Flamigo, Dragonite, Sableye, and of course, Kyurem White.  




