---
title: "A Network Map of the Current Meta"
description: |
  Sneak peek into the next meta
author:
  - name: melondonkey
    url:
      {https://pokemon-data-analysis.netlify.app}
date: 2024-02-16
output:
  distill::distill_article:
    self_contained: true
---

It's been a while.

The gen 9 meta has seen balanced, open play that favors good, consistent players over cheap gimmicks, which has not exactly been my cup of tea.  Terastalization has made data analysis difficult as well, so I just haven't felt like I've had much to contribute here.  Then I remembered, though, that I never really had that much to contribute to begin with--that I was just doing this for fun.  So in that spirit I bring you another fun project--a network diagram of the current meta.  

I like to go a bit beyond usage statistics and look at how mons are used together.  The best way to do this, I believe, is by looking at match-level data and clustering the results.  I've done this before in previous posts using a Bernouli mixture model.  There's an example [here](https://pokemon-data-analysis.netlify.app/posts/2022-04-05-more-data-more-cores/) from the Gen8 restricted meta.

I haven't racked up as many Showdown! games in this meta though (for one the format changes almost every month).  The next best thing, then, is to look at the usage and co-occurrence statistics from smogon.  Using these, we can at least map the associations of which mons are used with which.  

So here it is.  You should be able to **zoom in**, select nodes to highlight with the drop-down, or just **click and drag** and have fun with it.  The nodes are obviously Pokemon (I filtered to those with at least 1% usage, I think).  The vertices are the conditional probability the less-used Pokemon is used with the greater-used.  Probably not what I'd use for a vertex in an ideal world but that's pretty much the only data to work with.  I'm open to suggestions for more useful ways to lay this out in the future.  

```{r, echo=FALSE}
library(here)
htmltools::includeHTML(here("meta-network.html"))
```